export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const CARDS_SHUFFLE = 'CARDS_SHUFFLE';
export const CARDS_MOVE_CARD = 'CARDS_MOVE_CARD';
export const CARDS_SHOW_FACE = 'CARDS_SHOW_FACE';
